// Generated by CoffeeScript 1.3.3
(function() {
  var LIB, helloWorld, prefIt, root;

  root = this;

  prefIt = root.LIB;

  LIB = function(obj) {
    if (obj instanceof LIB) {
      return obj;
    }
    if (!(this instanceof LIB)) {
      return new LIB(obj);
    }
  };

  if (typeof exports !== 'undefined') {
    LIB = exports;
  } else {
    LIB = root.LIB = {};
  }

  LIB.VERSION = '0.01';

  helloWorld = LIB.helloWorld = function() {
    return "Hello World!";
  };

}).call(this);
