// Generated by CoffeeScript 1.3.3
(function() {
  var LIB, exports, helloWorld, prefIt, root;

  root = this;

  prefIt = root.LIB;

  LIB = function(obj) {
    if (obj instanceof LIB) {
      return obj;
    }
    if (!(this instanceof LIB)) {
      return new LIB(obj);
    }
    return this._wrapped = obj;
  };

  if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
      exports = module.exports = LIB;
    }
    exports.LIB = LIB;
  } else {
    root.LIB = LIB;
  }

  LIB.VERSION = '0.01';

  helloWorld = LIB.helloWorld = function() {
    return "Hello World!";
  };

}).call(this);
